Debugger: Format changes only
AppleWin/AppleWin pull request #1076
Opened 2022-03-27 22:05 UTC by kiyolee

- Fix some inconsistent indentations
- Add some curly brackets to clarify structure

2022-04-01 22:21 UTC, Michaelangel007 commented
In the future please run all formatting changes for the debugger by me. Some of these are fine, some are not.

Also, smaller PRs are easily to review & accept.

Thx.

2022-04-01 23:14 UTC, kiyolee commented
Please just point out which parts you don't like, I can easily fix that.
I guess another common divisive style choice is whether to have extra indentation in front of case tags and how each case block should indent.
I have no interest of pushing personal perference around.
I isolated all these format changes out is mainly to avoid mixing these up with upcoming PRs and so those PRs hopefully can be easier to read.
Some of these format changes were done to help myself to understand the code better while I am making other changes.
I am equally happy if this PR is completely rejected and then I will avoid touching any of these format in upcoming PRs.

2022-04-02 02:49 UTC, Michaelangel007 requested changes

2022-04-02 02:49 UTC, Michaelangel007 commented on source/Debugger/Debug.cpp
> +	char *pText;
This should be reverted as pText and nSize are aligned. Thanks.

2022-04-02 02:49 UTC, Michaelangel007 commented on source/Debugger/Debug.cpp
> +				case PS_LITERAL:
These case statements needs to be reverted (should be indented.)

2022-04-02 02:49 UTC, Michaelangel007 commented on source/Debugger/Debug.cpp
> +	//g_bConsoleBufferPaused = true;
Another good catch. Thx!

2022-04-02 02:49 UTC, Michaelangel007 commented on source/Debugger/Debugger_Display.cpp
> +		rect.top += nFontHeight;
This is another good catch. Thx.

2022-04-02 02:51 UTC, Michaelangel007 commented
OK, I've finished the review.  Overall this has some good catches and cleanup that is long over due.

There is some minor cleanup before I'll can accept this PR:

* case statements need to be reverted and indented
* misc. type / variable alignment

Thanks for doing the grunt work of cleanup.

2022-04-02 10:28 UTC, kiyolee commented on source/Debugger/Debugger_Disassembler.cpp
> +				// Intentional fall through. // REVIEW??
@Michaelangel007 Is the fall through intentional?

2022-04-02 10:28 UTC, kiyolee commented on source/Debugger/Debug.cpp
> +						//Transpose16x1::transposeFrom16x1( pSwizzled, (uint8_t*) pChromaTable );
This is new.

2022-04-02 10:29 UTC, kiyolee commented on source/Debugger/Debugger_Disassembler.cpp
> +	uint8_t		negative;
Fixed in new commit.

2022-04-02 10:29 UTC, kiyolee commented on source/Debugger/Debugger_Disassembler.cpp
> +		case NOP_BYTE_1:
Reverted in new commit.

2022-04-02 10:29 UTC, kiyolee commented on source/Debugger/Debug.cpp
> +	char *pText;
Reverted in new commit.

2022-04-02 10:30 UTC, kiyolee commented on source/Debugger/Debug.cpp
> +				case PS_LITERAL:
Reverted in new commit.

2022-04-02 18:14 UTC, Michaelangel007 commented on source/Debugger/Debug.cpp
> +						//Transpose16x1::transposeFrom16x1( pSwizzled, (uint8_t*) pChromaTable );
Looks fine.

2022-04-02 18:14 UTC, Michaelangel007 commented on source/Debugger/Debug.cpp
> +	char  *pText;
👍

2022-04-02 18:15 UTC, Michaelangel007 commented on source/Debugger/Debugger_Disassembler.cpp
> +	bool     isZero;
Thanks for fixing this.

2022-04-02 18:20 UTC, Michaelangel007 commented on source/Debugger/Debugger_Disassembler.cpp
> +				// Intentional fall through. // REVIEW??
I think that's a bug?  Thanks for the catch.  For now add a `break` until I setup a test case to exercise if the fall through is needed or not.

2022-04-02 18:20 UTC, Michaelangel007 approved these changes
Looks good. Thanks!

2022-04-02 18:37 UTC, Michaelangel007 commented on source/Debugger/Debug.cpp
> +				case PS_LITERAL:
👍 Thanks!

2022-04-02 23:22 UTC, Michaelangel007 approved these changes
Thanks

2022-04-02 23:23 UTC, Michaelangel007 commented
@tomcw This PR is ready to be merged.  A quick set of eyes wouldn't hurt.

2022-04-03 17:15 UTC, merged

2022-04-03 17:21 UTC, tomcw commented
LGTM - merged it.

2022-04-05 01:16 UTC, Michaelangel007 commented
@tomcw Thanks!