Uthernet II: add virtual DNS feature
AppleWin/AppleWin pull request #1097
Opened 2022-04-30 17:56 UTC by audetto

Hi this PR adds a new feature to the Uthernet II card (not found on real hardware).

**Virtual DNS**: the card offers an interface for DNS resolution, allowing Apple ][ software to run **without** raw sockets.
And as a consequence, `pcap` is not needed, allowing operation on non-Ethernet networks.

There is a description of this feature at: https://github.com/a2retrosystems/uthernet2/wiki/Virtual-W5100-with-DNS
An example of an application using this feature is https://github.com/oliverschmidt/A2Stream

Non-DNS related changes

1. A new save state version for Uthernet II has been added.
2. Long standing issue of where the Uthernet flags are read has been resolved, They are now read in the constructor of the cards.
3. Ethernet configuration has been changed. `pcap` is not compulsory any longer, but without, only U II software dns-aware has any chance to work. This is mentioned in the configuration dialog.

2022-05-01 09:55 UTC, audetto commented
And ensure npcap's usage is always protected from inside `tfearch.cpp`.

This means as well that `SS_YAML_KEY_CANNOT_USE` from Uthernet 1 SaveState is ignored.

2022-05-01 14:20 UTC, tomcw commented
@audetto - in DNS.cpp, can you add the license header at the start of the file (ie. same as you did for Uthernet2.cpp).

2022-05-07 18:12 UTC, tomcw requested changes

2022-05-07 18:12 UTC, tomcw commented on resource/Applewin.rc
> +    GROUPBOX        "Npacp",IDC_STATIC,5,75,260,55
There's a minor typo here: should be "Npcap"

2022-05-07 18:12 UTC, tomcw commented on source/W5100.h
> +#define W5100_SN_VIRTUAL_DNS      0x08
Can you add a comment to say that this doesn't exist on a real W5100.

2022-05-07 20:31 UTC, audetto commented on resource/Applewin.rc
> +    GROUPBOX        "Npacp",IDC_STATIC,5,75,260,55
changed

2022-05-07 20:31 UTC, audetto commented on source/W5100.h
> +#define W5100_SN_VIRTUAL_DNS      0x08
done

2022-05-08 15:22 UTC, tomcw approved these changes

2022-05-08 15:26 UTC, merged

2022-05-08 15:40 UTC, tomcw commented
@audetto - thanks for this work - it's now merged into the mainline.

2022-05-08 16:04 UTC, tomcw commented
Test both a wired (my desktop) and a wireless (my laptop) connection - both working fine.

2022-05-08 16:05 UTC, audetto commented
Cool.
Do you think we could / should change the default to TRUE for this feature?

2022-05-08 16:52 UTC, tomcw commented
ie. should we make "Virtual DNS" the default when "Uthernet II" is selected?

I quickly tested Contiki (webbrowser) and A2Stream v1.0, and both worked fine with "Virtual DNS" checked.
NB. Only at A2Stream v1.2 was DNS offloading support added.

So for a better end-user experience then it seems like a good thing to make "Virtual DNS=TRUE" the default setting.
Are there any reasons not to do this?

2022-05-27 21:03 UTC, tomcw commented
@audetto, @oliverschmidt:
New AppleWin release with this DNS offload support: https://github.com/AppleWin/AppleWin/releases/tag/v1.30.10.0

2022-05-27 21:26 UTC, sicklittlemonkey commented
Awesome work guys. What a great release!

2022-06-05 19:57 UTC, oliverschmidt commented
Thanks for the release 😊

Here's the promised video - https://youtu.be/5oddV-wMyqg