Add support for hardware copy protection dongles
AppleWin/AppleWin pull request #1154
Opened 2022-12-14 07:09 UTC by medasaro

This change adds support for hardware copy protection dongles.

Changes:
- Add a pulldown menu to the 'Advanced' tab that lets the user select a dongle in use
- Add a new file "CopyProgtectionDongles.cpp" that is a place to put drivers for these.
- Add a driver for the one known dongle we have now - Speed Star
- Modify Memory.cpp to alert the copy protection drivers when AN0-AN3 change
- Modify Joystick.cpp to allow PB0-PB2 to be "pushed" by the protection dongle.
- Misc.

Note: This is my first time contributing to this project, and my first time attempting to use git. Please go easy on me if I have made some dumb mistakes.

2022-12-14 20:40 UTC, medasaro commented
Here is a simple test program I wrote to verify the functionality of the Speed Star protection dongle. Also attached is the expected output on real hardware.

-Matthew D'Asaro

[SoftKey Truth Table.zip](https://github.com/AppleWin/AppleWin/files/10231507/SoftKey.Truth.Table.zip)

2022-12-14 22:11 UTC, tomcw commented
This is looking pretty good. Some minor things:

---

Rename these vars/funcs/enums/macros to use _non-truncated_ words:
- REGVALUE_CPYPRTDONGLE_TYPE -> REGVALUE_COPYPROTECTIONDONGLE_TYPE
- CPageAdvanced::InitCpyPrtDongleDropdownMenu() -> CPageAdvanced::InitCopyProtectionDongleDropdownMenu()
- m_CopyPrtDongleChoices[] -> m_CopyProtectionDongleChoices[]
- cpyPrtDongleType -> g_copyProtectionDongleType
- CPYPRTDONGLETYPE -> COPYPROTECTIONDONGLETYPE
- SetCpyPrtDongleType() -> SetCopyProtectionDongleType()
- GetCpyPrtDongleType() -> GetCopyProtectionDongleType()
- CopyProtDongleControl() -> CopyProtectionDongleControl()
- CopyProtDonglePB*() -> CopyProtectionDonglePB*()
- ...there may be others

---

Change all 3x CopyProtDonglePB*() funcs to return bool instead of DWORD.
Reason: SdsSpeedStar() returns a bool, but CopyProtDonglePB2() returns a DWORD here:
```
DWORD CopyProtDonglePB2(void)
{
	switch (cpyPrtDongleType)
	{
	case SDSSPEEDSTAR:	// Southwestern Data Systems SoftKey for Speed Star Applesoft Compiler
		return SdsSpeedStar();
```

---

PageAdvanced.cpp needs a final newline after that final `}` at the very end of the file.

---

Remove this code from Memory.cpp:

```
if (address >= 0xC058 && address <= 0xC05F)
		CopyProtDongleControl(address);	// Update AN0 - AN3 state for copy protection dongles
```

Instead call `MemGetAnnunciator(UINT annunciator)` to get the values of annunciators.

Then you can remove the 4x `static bool g_AN*` vars and `CopyProtDongleControl(const UINT uControl)` in "CopyProtectionDongles.cpp".

---

You've added a new .cpp file, so you'll need to include the AppleWin.vcxproj & AppleWin.vcxproj.filters files in this PR too.

---

btw, static bool g_AN* is internal state, which needs to be persisted or init'ed when loading a save-state. Probably the latter, since it's just a copy of Memory.cpp's `g_Annunciator[4]` variables. But if you can remove these 4x static bool g_AN*, as I suggest above, then even better.

But don't worry about save-state... I can add the support for this (and we'll also need to persist the `cpyPrtDongleType`).

Thanks!

2022-12-15 05:36 UTC, medasaro commented
Thank you so much @tomcw for your helpful and detailed suggestions for improving my PR. I have implemented all of them except for "Change all 3x CopyProtDonglePB*() funcs to return bool instead of DWORD." If you note, I am using a return value of -1 to indicate that the copy protection dongle is not using a specific PB*. A return value of -1 is caught in Joystick.cpp: `				if(CopyProtectionDonglePB0() >= 0)				//If a copy protection dongle needs PB0, this overrides the joystick
					pressed = CopyProtectionDonglePB0();`

I am going to let you handle the save state as you offered - I looked at that code and it is not quite clear to me how it works.

Thanks,
Matthew D'Asaro

2022-12-15 08:13 UTC, tomcw requested changes
With the addition of those .vcxproj files, Visual Studio has "helpfully" made some changes that I'll need you to undo:
(eg. for `WindowsTargetPlatformVersion` and `PlatformToolset`)

- AppleWinExpress2019.vcxproj
- yaml2019.vcxproj
- TestCPU6502-vs2019.vcxproj
- zip_lib2019.vcxproj
- zlib-Express2019.vcxproj

I've annotated with "Revert this." comments.

2022-12-15 08:13 UTC, tomcw commented on AppleWinExpress2019.vcxproj
> +    <WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>
Revert this.

2022-12-15 08:13 UTC, tomcw commented on AppleWinExpress2019.vcxproj
> +    <PlatformToolset>v141</PlatformToolset>
Revert this.

2022-12-15 08:13 UTC, tomcw commented on libyaml/win32/yaml2019.vcxproj
> +    <WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>
Revert this.

2022-12-15 08:13 UTC, tomcw commented on libyaml/win32/yaml2019.vcxproj
> +    <PlatformToolset>v141</PlatformToolset>
Revert this.

2022-12-15 08:13 UTC, tomcw commented on test/TestCPU6502/TestCPU6502-vs2019.vcxproj
> +    <WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>
Revert this.

2022-12-15 08:13 UTC, tomcw commented on test/TestCPU6502/TestCPU6502-vs2019.vcxproj
> +    <PlatformToolset>v141</PlatformToolset>
Revert this.

2022-12-15 08:13 UTC, tomcw commented on zip_lib/zip_lib2019.vcxproj
> +    <WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>
Revert this.

2022-12-15 08:13 UTC, tomcw commented on zip_lib/zip_lib2019.vcxproj
> +    <PlatformToolset>v141</PlatformToolset>
Revert this.

2022-12-15 08:13 UTC, tomcw commented on zlib/zlib-Express2019.vcxproj
> +    <WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>
Revert this.

2022-12-15 08:13 UTC, tomcw commented on zlib/zlib-Express2019.vcxproj
> +    <PlatformToolset>v141</PlatformToolset>
Revert this.

2022-12-16 01:04 UTC, medasaro commented
I believe I have resolved the corrupted project file issue with my latest commit. Sorry about that.

-Matthew D'Asaro

2022-12-16 01:07 UTC, medasaro commented
Hmm. I don't think I meant to "close" this. Reopening.

-Matthew D'Asaro

2022-12-16 08:55 UTC, tomcw approved these changes

2022-12-16 09:04 UTC, merged

2022-12-16 09:12 UTC, tomcw commented
Thanks @medasaro - successfully merged into the main line!
btw, I'll add a credit to you in the docs & history for this contribution.