Breakpoints: some new features
AppleWin/AppleWin pull request #1191
Opened 2023-03-03 20:14 UTC by audetto

I would like to propose this PR with a few new features for breakpoints.

First, a little disclosure: I am trying to integrate AppleWin (linux only) into this debugger for CC65 https://github.com/empathicqubit/vscode-cc65-debugger. To achieve this, I need to implement the VICE binary monitor protocol https://vice-emu.sourceforge.io/vice_13.html which requires these (little) extensions to breakpoints.

But, you can simply ignore all the above and look at these features, which I think have a value on their own.

1. add a hit count
2. add a `bStop` flag. if `false` only the hit count is incremented
3. add a `bHit` flag, so it is possible to query which breakpoint(s) have caused the debugger to stop
4. keep temporary breakpoints alive a bit longer, so they can be inspected

In order to ease the debugging I have added a new command `BPCHANGE` to individually change the flags.
`BPL` has been changed to display all the new information.

What do people think of the idea? And, second question, what about the implementation?

2023-03-04 11:18 UTC, tomcw commented
>What do people think of the idea? 

I don't have any strong objections to this integration.

In fact over the years, I've been considering adding gdb/lldb server support (+ useful for unit-testing & scripting too).
I've certainly spoken to @sicklittlemonkey about this in the past.

@Michaelangel007 what are your thoughts?

For my info, it looks like VICE's "binary monitor" interface is via TCP/IP (specifically localhost:port).
Ref: https://vice-emu.sourceforge.io/vice_6.html#SEC135

You say it's Linux only. Why can't this be supported by Windows too?

2023-03-04 12:22 UTC, sicklittlemonkey commented on source/Debugger/Debug.cpp
> +	// should this check if breakpoints are actually enabled?
Who is this question for? ; - )
// should this check if breakpoints are actually enabled?

2023-03-04 12:46 UTC, sicklittlemonkey commented
I think this sounds really cool. Visual Studio is a popular platform, so it makes a lot of sense.
VICE has a lot of history and seems to have momentum behind it, so hopefully it's well done.
(I don't like the binary protocol much, but that doesn't matter at all.)

We've sure have talked about this kind of stuff a few times over the years, Tom.
And remember in Tokyo I showed you my Java Apple II emulator running inside Eclipse.
That must be over 20 years ago now! Writing debugger plug-ins was a bit tough back then.

It would be nice to have this working in the Windows version eventually.
I stole some socket code from GSport which worked in both Linux and Windows.
It's not difficult, but I can dig it up if you want. Anyway, the Windows side could come later.

(I still plan to get my "KiwiPad" (KoalaPad mobile app) working in AppleWin again some day.)

2023-03-04 15:24 UTC, audetto commented on source/Debugger/Debug.cpp
> +	// should this check if breakpoints are actually enabled?
For anyone who can answer.

As a very minor optimisation (and unrelated to this change), we should really count the number of breakpoints that are enabled, not just existing, to decide if we can leave the debugging mode. Because anyway, none of them can trigger if disabled.

2023-03-04 15:28 UTC, audetto commented
Why not Windows?

1) not to scare people with a big PR :-)
2) but really because I am still fighting with it, so I cannot yet comment how well integrated / encapsulated looks like or needs to be.

But it looks like breakpoints are the most important part of a good debugger, so I thought of up-streaming this to begin with.

2023-03-09 23:05 UTC, tomcw commented
@Michaelangel007 - any thoughts?

2023-03-12 17:24 UTC, tomcw commented
>And, second question, what about the implementation?

I've had a look, and it seems fine, ie. consistent with existing code, and just extends existing functionality.
From my POV, it's fine to merge it in.

@Michaelangel007 - I'll give you more time to consider this.

2023-03-19 14:13 UTC, Michaelangel007 commented
Just some minor coding style fixes to be consistent with my debugger standards, other then that looks good!

2023-03-19 14:49 UTC, Michaelangel007 commented
The temp breakpoint is an interesting idea.

I took a look at the "new" UI.  Seems fine.  We probably should colorize the addresses and symbol name resolution but that can be done at another time in a cleanup pass since I don't want to bikeshed this PR.

2023-03-19 15:07 UTC, Michaelangel007 commented
@audetto Thanks for providing the context and link to VICE.

@tomcw In that VICE thread empathicqubit brought up an interesting point:  _It would be best if AppleWin could handle disk creation_

Obviously we are never going to replace [CiderPress](https://github.com/fadden/ciderpress) or [Cadius](https://www.brutaldeluxe.fr/products/crossdevtools/cadius/)  but is **minimal disk creation** something that we should consider Out-of-the-Box for AppleWin? I could "recycle" some of the code for my [ProDOS utils](https://github.com/Michaelangel007/apple2_prodos_utils).  (I wrote it because Mark was mentioning building the _Nox Archaist_ virtual disks was dog slow.  At some point I'd like to make a fast multithreaded "disk layout" but got sidetracked onto other projects.)

2023-03-19 16:27 UTC, audetto commented
> Just some minor coding style fixes to be consistent with my debugger naming conventions / code standards, other then that looks good!

Where?

> Probably should add a proper row header for `BPL` at some point.

Like this?

> ```
> ID  Enabled Stop Temp Hit Counter  Address Symbol
> #0  E       S    -    *   00000000 C000    KEYBOARD                                           
> #15 E       S    -        00000000 0300    $300
> ```

And I guess I need to decouple the display for Bookmarks and Watches to keep their existing layout.

2023-03-19 17:26 UTC, Michaelangel007 requested changes
Ah, helps if I click `Finish your review`.  Sorry about that.

2023-03-19 18:23 UTC, audetto commented on source/Debugger/Debug.cpp
> +	int  iBreakpointHit = 0;
Done

2023-03-19 18:23 UTC, audetto commented on source/Debugger/Debug.cpp
> +			case 'E':
Done. Should I print some error for invalid characters?

2023-03-19 18:23 UTC, audetto commented on source/Debugger/Debug.cpp
> +	static const char sEnabledFlags[] = "-E";
Done.

2023-03-19 18:23 UTC, audetto commented on source/Debugger/Debugger_Types.h
> +		bool                 bHit;     // true when the breakpoint has just been hit
Done

2023-03-19 18:46 UTC, Michaelangel007 approved these changes
LGTM. Ship it!

2023-03-20 13:25 UTC, merged

2023-03-21 17:06 UTC, Michaelangel007 commented
I haven't had a chance to test that function (I probably won't get a chance to look at this until tomorrow) but the cleanup I was referring to is:

1. Separate entries for each character `EeSsTt` respectively should be added to `g_aParameters[] =`, Debugger_Commands, Line 421

```c
		{TEXT("*")          , NULL, PARAM_BP_READ_WRITE     },

    // Breakpoint Change, See: CmdBreakpointChange ()
		{TEXT("E")          , NULL, PARAM_BP_CHANGE_ENABLE   },
		{TEXT("e")          , NULL, PARAM_BP_CHANGE_DISABLE  },
		{TEXT("T")          , NULL, PARAM_BP_CHANGE_TEMP_ON  },
		{TEXT("t")          , NULL, PARAM_BP_CHANGE_TEMP_OFF },
		{TEXT("S")          , NULL, PARAM_BP_CHANGE_STOP_ON  },
		{TEXT("s")          , NULL, PARAM_BP_CHANGE_STOP_OFF },
```

2. Update `Parameters_e`, Debugger_Types.h, Line 1366:

```c
	, _PARAM_BP_CHANGE_BEGIN = _PARAM_BREAKPOINT_END // Daisy Chain
		, PARAM_BP_CHANGE_ENABLE   // E
		, PARAM_BP_CHANGE_DISABLE  // e
		, PARAM_BP_CHANGE_TEMP_ON  // T
		, PARAM_BP_CHANGE_TEMP_OFF // t
		, PARAM_BP_CHANGE_STOP_ON  // S
		, PARAM_BP_CHANGE_STOP_OFF // s
	, _PARAM_BP_CHANGE_END
	,  PARAM_BP_CHANGE_NUM = _PARAM_BP_CHANGE_END - _PARAM_BP_CHANGE_BEGIN

	, _PARAM_REGS_BEGIN = _PARAM_BP_CHANGE_END // Daisy Chain
```

2023-03-21 20:45 UTC, audetto commented
Got it.

I realise that `FindParam` does a case insensitive match, so the `E` vs `e` is lost.

I will instead code it as `bpchange 1 stop on` or `bpchange 2 stop off` etc...

I see there is a `bpedit` function, but it seems not to do anything, should I re-purpose it for this?

2023-03-22 01:21 UTC, Michaelangel007 commented
Ah, I see the problems with `FindParam`. 

1. The second param `MATCH_EXACT` should do a case sensitive search (but it doesn't), and
2. `ALLOW_INPUT_LOWERCASE` is set to 1 forcing `MATCH_FUZZY`.

Technically you don't need `FindParam()`, I was thinking of the simpler:

```c
				case g_aParameters[ PARAM_BP_CHANGE_ENABLE   ]: bp.bEnabled = true ; break;
				case g_aParameters[ PARAM_BP_CHANGE_DISABLE  ]: bp.bEnabled = false; break;
				case g_aParameters[ PARAM_BP_CHANGE_TEMP_ON  ]: bp.bTemp    = true ; break;
				case g_aParameters[ PARAM_BP_CHANGE_TEMP_OFF ]: bp.bTemp    = false; break;
				case g_aParameters[ PARAM_BP_CHANGE_STOP_ON  ]: bp.bStop    = true ; break;
				case g_aParameters[ PARAM_BP_CHANGE_STOP_OFF ]: bp.bStop    = false; break;
```

Let me take a look at `bpedit` and see if we should use that ...

2023-03-22 01:28 UTC, Michaelangel007 commented
Ah, yeah, `CmdBreakpointEdit()` was never finished.  I envisioned it as interactive editor (kind of like a sector editor) where you could use the arrow keys to move among breakpoints and change the breakpoint type.

Let's leave `CmdBreakpointEdit()` for that purpose.

2023-03-22 20:03 UTC, audetto commented
> ```c
> case g_aParameters[ PARAM_BP_CHANGE_ENABLE   ]: bp.bEnabled = true ; break;
> ```

Without making this a too big of a deal, this is invalid as not constant.
At the same time, I have realised that needing the correct case is awkward and non standard.

I believe the best I can suggest is: `bpchange 1 enable off` and so on. What do you think?

2023-03-23 02:31 UTC, Michaelangel007 commented
Oh yeah, the stupid compiler can't optimize that switch statement when `const Command_t g_aParameters[];`

That actually brings up a good point, that I should do some const cleanup on `Command_t`, specifically `const char   m_sName[ MAX_COMMAND_LEN ];` but I see that is going to take some minor work.

I'd rather keep the single character params since I hate typing words for arguments. =P

I'll fixup `FindParam()` so `MATCH_EXACT` works correctly, and then fix `CmdBreakpointChange() so it uses it which will solve the problem.

i.e. This works:

```
Update_t CmdBreakpointChange (int nArgs) {

	if (! g_nBreakpoints)
		return ConsoleDisplayError("There are no (PC) Breakpoints defined.");

	if (nArgs < 2)
		return Help_Arg_1( CMD_BREAKPOINT_CHANGE );

	const int iSlot = g_aArgs[1].nValue;
	if (iSlot >= 0 && iSlot < MAX_BREAKPOINTS && g_aBreakpoints[iSlot].bSet)
	{
		Breakpoint_t & bp = g_aBreakpoints[iSlot];
		int iParam;
		int iParamArg = nArgs;	// last arg is the 'ON' / 'OFF' param
		for (int iParamArg = 2; iParamArg <= nArgs; ++iParamArg)
		{
			int bFound = FindParam( g_aArgs[ iParamArg ].sArg, MATCH_EXACT, iParam, _PARAM_BP_CHANGE_BEGIN, _PARAM_BP_CHANGE_END, true );
			if (! bFound)
				return Help_Arg_1( CMD_BREAKPOINT_CHANGE );

			switch (iParam)
			{
				case PARAM_BP_CHANGE_ENABLE  : bp.bEnabled = true ; break;
				case PARAM_BP_CHANGE_DISABLE : bp.bEnabled = false; break;
				case PARAM_BP_CHANGE_TEMP_ON : bp.bTemp    = true ; break;
				case PARAM_BP_CHANGE_TEMP_OFF: bp.bTemp    = false; break;
				case PARAM_BP_CHANGE_STOP_ON : bp.bStop    = true ; break;
				case PARAM_BP_CHANGE_STOP_OFF: bp.bStop    = false; break;
			}
		}
	}

	return UPDATE_BREAKPOINTS;
}
```

2023-03-23 03:38 UTC, Michaelangel007 commented
> ID  Enabled Stop Temp Hit Counter  Address Symbol

This has been fixed with commit b7263bb1.