Debugger step over
AppleWin/AppleWin pull request #1203
Opened 2023-03-26 22:17 UTC by Michaelangel007

New behavior. Detect stack state after `JSR` (3 possible states).

1. RTS on stack but extra junk on stack
![1_step_over_0x1f1](https://user-images.githubusercontent.com/7876796/227807973-90fb3a8a-ee55-448b-80d0-6dffa3e99a34.png)

2. RTS on stack, no extra junk on stack
![2_step_over_0x1f2](https://user-images.githubusercontent.com/7876796/227807995-d24beadc-3086-4360-8024-16c8dccdb483.png)

3. RTS not found on stack (!)
![3_step_over_0x1f3](https://user-images.githubusercontent.com/7876796/227808049-771c46c0-b1d4-499e-b977-c03c143bbc15.png)

4. Successful step over, like 2 but with increased max execution steps.
![4_step_over](https://user-images.githubusercontent.com/7876796/227808065-14c72dfa-7502-4768-a980-8f590b779198.png)

2023-03-27 20:17 UTC, tomcw requested changes

2023-03-27 20:17 UTC, tomcw commented on source/Debugger/Debugger_Assembler.cpp
> +	unsigned nStack = regs.sp;
"unsigned" is missing a type... assume `WORD`
And in 2 other occurrences below...

2023-03-27 20:17 UTC, tomcw commented on source/Debugger/Debugger_Assembler.cpp
> +		nStack++;
Need to handle the wraparound case for this `nStack++`, eg:
`nStack = ((nStack+1)&0xff)+0x100;`

2023-03-27 20:17 UTC, tomcw commented on source/Debugger/Debugger_Assembler.cpp
> +		if (nReturnAddress ==nAddress)
Missing a space after `==`.

2023-03-27 20:17 UTC, tomcw commented on source/Debugger/Debugger_Assembler.cpp
> +	return 0; // not found
I haven't fully traced the logic, but isn't a value of 0(zero) a valid stack offset?
So maybe return -1 instead for this "not found" case.

2023-03-27 23:03 UTC, Michaelangel007 commented on source/Debugger/Debugger_Assembler.cpp
> +	unsigned nStack = regs.sp;
Fixed f8533d5c

2023-03-27 23:03 UTC, Michaelangel007 commented on source/Debugger/Debugger_Assembler.cpp
> +		if (nReturnAddress ==nAddress)
Fixed 29796e4e

2023-03-27 23:10 UTC, Michaelangel007 commented on source/Debugger/Debugger_Assembler.cpp
> +		nStack++;
Interesting edge case, when sp = 0x101.  Need to track down why this assert is triggering: `_ASSERT(g_nAppMode == MODE_RUNNING || g_nAppMode == MODE_STEPPING);`

2023-03-28 15:31 UTC, Michaelangel007 commented on source/Debugger/Debugger_Assembler.cpp
> +	return 0; // not found
Thanks for the catch.  Fixed with f8bdedcc

2023-03-28 15:32 UTC, Michaelangel007 commented on source/Debugger/Debugger_Assembler.cpp
> +		nStack++;
Fixed with commit c49569fa

2023-03-28 15:36 UTC, Michaelangel007 commented
@tomcw Should be all fixed now. I've also clarified how to repro/test the old behavior.

2023-03-28 19:39 UTC, tomcw requested changes

2023-03-29 14:48 UTC, Michaelangel007 commented on source/Debugger/Debugger_Assembler.cpp
>  int _6502_FindStackReturnAddress (const WORD & nAddress)
Thanks for catching that old habit pass-by-ref.

I've cleaned up all the stack return address with `_6502_PeekStackReturnAddress()`.

Also, `_6502_GetStackReturnAddress()` no longer returns a redundant bool but the actual return address.  This caused a minor cascade cleanup in `CmdStepOut()` and `CmdCursorJumpRetAddr()`.

Fixed with commit 55f863d1

2023-03-29 15:35 UTC, Michaelangel007 commented
@tomcw What's the protocol for `Resolve Conversation`  ? The person who opened the PR or the reviewer?  TIA.

2023-03-29 19:36 UTC, tomcw commented on source/Debugger/Debugger_Assembler.cpp
> +	       nAddress  = ((unsigned) *(LPBYTE)(mem + 0x100 + (nStack & 0xFF))     ); nStack++;
Since `nStack` is an input and output, then you need to wrap it correctly:
`nStack = 0x100 + ((nStack+1) & 0xff);`

Hmm, actually since _currently_ it's only used afterwards by `_6502_FindStackReturnAddress()`, then for this specific case when it overflows (ie. IN: nStack = 0x1ff, OUT: nStack = 0x200), then you use `nStack` afterwards here:

```
nDepth = (nStack - 2 - regs.sp);
```

So for this overflow case: nDepth = 0x200 - 2 - regs.sp = 0x1fe - regs.sp... so perhaps fine?
... and nDepth = 0x200 - 2 - 0x1fe = 0.

So looks to be fine.

---

At the other extreme... IN: nStack=0x100, OUT: nStack=0x101

So for this case: nDepth = 0x101 - 2 - regs.sp = 0x0ff - regs.sp... which doesn't look right to me, since regs.sp is >= 0x100, so nDepth is a negative value.

OK, ignore me for this case, since `nStack = regs.sp + 1`, so as a minimum IN: nStack=0x101, OUT: nStack=0x102
... and nDepth = 0x102 - 2 - 0x100 = 0.

---

In conclusion it all seems fine.

Could you add a comment after this line "// NOTE: nStack is both an input and output", just saying that the overflow for the case when nStack=0x1ff and returns with 0x200 is fine, since the calling function accounts for this.

2023-03-29 22:14 UTC, Michaelangel007 commented on source/Debugger/Debugger_Assembler.cpp
> +	       nAddress  = ((unsigned) *(LPBYTE)(mem + 0x100 + (nStack & 0xFF))     ); nStack++;
Added note with commit 64b4fb77

2023-03-31 08:39 UTC, tomcw commented on source/Debugger/Debugger_Assembler.cpp
> +	       nAddress  = ((unsigned) *(LPBYTE)(mem + 0x100 + (nStack & 0xFF))     ); nStack++;
Thanks Michael - all looks fine now.

2023-03-31 08:45 UTC, merged